# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["oss@fastly.com"]
description = "Implements WebSockets passthrough"
language = "javascript"
manifest_version = 3
name = "WebSockets passthrough JavaScript"

[scripts]
build = "npm run build"
post_init = "npm install"
